#!/usr/bin/env python3
"""Plot curated Ny=2Nx comparison cases from manifest.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def load_typed(path: Path):
    out = {4: [], 5: [], 7: []}
    with path.open() as f:
        for line in f:
            if not line.strip() or line.startswith("#"):
                continue
            t_s, r_s, c_s, e_s = line.split()
            t = int(t_s)
            if t in out:
                out[t].append((int(r_s), float(c_s), float(e_s)))
    return out


def periodic_fractional_series(pts, L):
    r = [x[0] for x in pts]
    c = [x[1] for x in pts]
    e = [x[2] for x in pts]
    rf = [ri / float(L) for ri in r]
    if rf and abs(rf[0]) < 1e-14:
        rf.append(1.0)
        c.append(c[0])
        e.append(e[0])
    return rf, c, e


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--manifest",
        default="K_from_BC/collab_ny2nx/output/manifest.json",
        help="Path to manifest generated by run_cases.py",
    )
    ap.add_argument(
        "--output",
        default="K_from_BC/collab_ny2nx/output/plots/correlators_fractional.png",
        help="Output figure path",
    )
    args = ap.parse_args()

    repo = Path(__file__).resolve().parents[2]
    manifest_path = (repo / args.manifest).resolve()
    out_path = (repo / args.output).resolve()

    m = json.loads(manifest_path.read_text())
    nx = int(m["nx"])
    ny = int(m["ny"])
    l_right = int(np.lcm(nx, ny))

    loaded = []
    for case in m["cases"]:
        dat_path = repo / case["copied_dat"]
        loaded.append((case, load_typed(dat_path)))

    all_low = []
    all_high = []
    for _case, data in loaded:
        for t, L in ((4, nx), (5, ny), (7, l_right)):
            _, c, e = periodic_fractional_series(data[t], L)
            for ci, ei in zip(c, e):
                all_low.append(max(ci - ei, 1.0e-16))
                all_high.append(ci + ei)

    log_min = np.log10(min(all_low))
    log_max = np.log10(max(all_high))
    span = log_max - log_min if log_max > log_min else 1.0
    ylim = (10 ** (log_min - 0.10 * span), 10 ** (log_max + 0.10 * span))

    n = len(loaded)
    fig, axs = plt.subplots(1, n, figsize=(6.2 * n, 5.0), sharey=True)
    if n == 1:
        axs = [axs]

    for ax, (case, data) in zip(axs, loaded):
        for t, L, label, fmt, color in [
            (4, nx, "x direction (base)", "o-", "#1f77b4"),
            (5, ny, "left/y direction", "s-", "#ff7f0e"),
            (7, l_right, "right direction (y-x)", "^-", "#2ca02c"),
        ]:
            rf, c, e = periodic_fractional_series(data[t], L)
            ax.errorbar(rf, c, yerr=e, fmt=fmt, ms=2.8, lw=1.15, capsize=1.9,
                        color=color, label=label)

        ax.set_title(
            f"{case['title']}\n"
            f"k1={case['k1']:.12f}, k2={case['k2']:.12f}, k3={case['k3']:.12f}",
            fontsize=10,
        )
        ax.set_xlabel("fractional separation r/L")
        ax.set_xlim(-0.02, 1.02)
        ax.set_yscale("log")
        ax.set_ylim(*ylim)
        ax.grid(alpha=0.25, which="both")

    axs[0].set_ylabel("connected correlator (log scale)")
    axs[-1].legend(loc="upper right", fontsize=7.4)
    fig.suptitle(
        f"Ny=2Nx comparison: connected correlators vs fractional separation\n"
        f"Lx={nx}, Ly={ny}, Lright=lcm(Nx,Ny)={l_right}",
        fontsize=12,
    )
    fig.tight_layout(rect=[0, 0, 1, 0.92])

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=190)
    print(out_path.relative_to(repo))


if __name__ == "__main__":
    main()
